@baseUrl = http://127.0.0.1:5000

# создания объявления
POST {{baseUrl}}/ads
Content-Type: application/json

{
  "title": "Продам велосипед",
  "description": "В хорошем состоянии",
  "owner": "Иван"
}

###

# Получение объявления с id=1
GET {{baseUrl}}/ads/1

###

# Редактирование объявления с id=1
PUT {{baseUrl}}/ads/1
Content-Type: application/json

{
  "title": "Продам велосипед (обновлено)",
  "description": "Состояние отличное, торг уместен"
}

###

# Удаление объявления с id=2
DELETE {{baseUrl}}/ads/1