--
-- PostgreSQL database dump
--

\restrict UqtN2ksJhBK0oBoSXmuT9aPvw4vgwBgSjad4hrcmiuhePctuDBtTbMeD9u6AMhk

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: main_phone; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_phone (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    price numeric(10,2) NOT NULL,
    image character varying(500) NOT NULL,
    release_date date NOT NULL,
    lte_exists boolean NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.main_phone OWNER TO postgres;

--
-- Name: main_phone_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_phone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_phone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add ╨в╨╡╨╗╨╡╤Д╨╛╨╜	7	add_phone
26	Can change ╨в╨╡╨╗╨╡╤Д╨╛╨╜	7	change_phone
27	Can delete ╨в╨╡╨╗╨╡╤Д╨╛╨╜	7	delete_phone
28	Can view ╨в╨╡╨╗╨╡╤Д╨╛╨╜	7	view_phone
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	main	phone
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-06-09 17:58:18.761567+03
2	auth	0001_initial	2026-06-09 17:58:18.925584+03
3	admin	0001_initial	2026-06-09 17:58:18.978885+03
4	admin	0002_logentry_remove_auto_add	2026-06-09 17:58:18.998386+03
5	admin	0003_logentry_add_action_flag_choices	2026-06-09 17:58:19.019773+03
6	contenttypes	0002_remove_content_type_name	2026-06-09 17:58:19.064206+03
7	auth	0002_alter_permission_name_max_length	2026-06-09 17:58:19.092961+03
8	auth	0003_alter_user_email_max_length	2026-06-09 17:58:19.115561+03
9	auth	0004_alter_user_username_opts	2026-06-09 17:58:19.13759+03
10	auth	0005_alter_user_last_login_null	2026-06-09 17:58:19.162051+03
11	auth	0006_require_contenttypes_0002	2026-06-09 17:58:19.165513+03
12	auth	0007_alter_validators_add_error_messages	2026-06-09 17:58:19.195783+03
13	auth	0008_alter_user_username_max_length	2026-06-09 17:58:19.232837+03
14	auth	0009_alter_user_last_name_max_length	2026-06-09 17:58:19.258877+03
15	auth	0010_alter_group_name_max_length	2026-06-09 17:58:19.295904+03
16	auth	0011_update_proxy_permissions	2026-06-09 17:58:19.318923+03
17	auth	0012_alter_user_first_name_max_length	2026-06-09 17:58:19.343584+03
18	main	0001_initial	2026-06-09 17:58:19.369298+03
19	sessions	0001_initial	2026-06-09 17:58:19.395712+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: main_phone; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_phone (id, name, price, image, release_date, lte_exists, description) FROM stdin;
1	Samsung Galaxy Edge 2	73000.00	/media/phones/1_Samsung_Galaxy_Edge_2.jpg	2016-12-12	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П: 1 ╨│╨╛╨┤ (╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╤М) | ╨б╤В╤А╨░╨╜╨░: ╨о╨╢╨╜╨░╤П ╨Ъ╨╛╤А╨╡╤П | ╨У╨╛╨┤: 2015 (╨╛╤В╨╝╨╡╨╜╨╡╨╜) | ╨Ь╨╛╨┤╨╡╨╗╤М: SM-G928E\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡: ╨╜╨╛╨▓╤Л╨╣ (╨╜╨╡ ╨▓╤Л╤И╨╡╨╗) | ╨С╤Л╤Б╤В╤А╨░╤П ╨╖╨░╤А╤П╨┤╨║╨░: ╨Ф╨░ | ╨С╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨░╤П ╨╖╨░╤А╤П╨┤╨║╨░: ╨Ф╨░\r\n\r\n╨Ю╨б\r\nAndroid 5.1 Lollipop\r\n\r\n╨н╨║╤А╨░╨╜\r\n5.5" / 2560x1440 (Super AMOLED, Gorilla Glass 4, 60 ╨У╤Ж)\r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nSnapdragon 808 (6 ╤П╨┤╨╡╤А) + Adreno 418\r\n\r\n╨Я╨░╨╝╤П╤В╤М\r\nROM: 32 ╨У╨С | RAM: 4 ╨У╨С | microSD: ╨┤╨╛ 128 ╨У╨С\r\n\r\n╨Ъ╨░╨╝╨╡╤А╨░\r\n╨Ю╤Б╨╜.: 16 ╨Ь╨Я (OIS, 4K) | ╨д╤А╨╛╨╜╤В.: 8 ╨Ь╨Я\r\n\r\nSIM\r\n1 nano-SIM\r\n\r\n╨б╨▓╤П╨╖╤М\r\n2G/3G/4G, Wi-Fi 5, NFC, Bluetooth 4.2\r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\nOTG, S-Pen, ╤Б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ (╨▓ ╨║╨╜╨╛╨┐╨║╨╡ Home)\r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨╡╤В╨░╨╗╨╗/╨┐╨╗╨░╤Б╤В╨╕╨║ | Micro USB | 3.5 ╨╝╨╝\r\n\r\n╨С╨░╤В╨░╤А╨╡╤П\r\n3000 ╨╝╨Р╤З, 15 ╨Т╤В\r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П, ╨║╨░╨▒╨╡╨╗╤М, ╨╜╨░╤Г╤И╨╜╨╕╨║╨╕
2	Iphone X	80000.00	/media/phones/2_Iphone_X.jpg	2017-06-01	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨Ъ╨╕╤В╨░╨╣ (╤Б╨▒╨╛╤А╨║╨░) / ╨б╨и╨Р (╤А╨░╨╖╤А╨░╨▒╨╛╤В╨║╨░)\r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2017\r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\niPhone\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nA1865 / A1901\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░\r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\niOS 11 (╨┤╨╛ iOS 16)\r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n5.8" / 2436x1125 ╨Я╨╕╨║╤Б\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n2436x1125 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nOLED Super Retina HD\r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\n╨Э╨╡ ╤Г╨║╨░╨╖╨░╨╜╨╛\r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n60 ╨У╤Ж\r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nApple A11 Bionic (2 x 2.39 + 4 ╤П╨┤╤А╨░)\r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\n╨▓╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ (Apple GPU)\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n6\r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n64 / 256 ╨У╨С\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n3 ╨У╨С\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n2 ╤И╤В\r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n12/12/0/0/0\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n3840x2160 ╨Я╨╕╨║╤Б (4K)\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n12/12/0/0/0\r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░ (╤Г ╨╛╨▒╨╡╨╕╤Е ╨║╨░╨╝╨╡╤А)\r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n10\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n12 ╨Ь╨Я╨╕╨║╤Б\r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo\r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В (TrueDepth)\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n7/0\r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n1 nano-SIM\r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE\r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 5 (802.11ac)\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n5.0\r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░\r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Ф╨░ (Face ID)\r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nLightning\r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\nLightning\r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╤Б╤В╨╡╨║╨╗╨╛/ ╨░╨╗╤О╨╝╨╕╨╜╨╕╨╣\r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIP67\r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Ф╨░\r\n╨Ъ╨░╨▒╨╡╨╗╤М Lightning - USB\r\n╨Ф╨░\r\n╨з╨╡╤Е╨╛╨╗\r\n╨Э╨╡╤В\r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Ф╨░ (EarPods ╤Б Lightning)\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n5 ╨Т╤В (╨▓ ╨║╨╛╨╝╨┐╨╗╨╡╨║╤В╨╡)\r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n2716 ╨╝╨Р╤З
3	Nokia 8	20000.00	/media/phones/3_Nokia_8.jpg	2013-01-20	f	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨д╨╕╨╜╨╗╤П╨╜╨┤╨╕╤П (╤А╨░╨╖╤А╨░╨▒╨╛╤В╨║╨░) / ╨Ъ╨╕╤В╨░╨╣ (╤Б╨▒╨╛╤А╨║╨░)\r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2017\r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nNokia\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nNokia 8\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (Quick Charge 3.0)\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 7.1.1 Nougat (╨╛╨▒╨╜╨╛╨▓╨╗╤П╨╡╨╝╨░╤П ╨┤╨╛ 9.0 Pie) \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n5.3" / 2560x1440 ╨Я╨╕╨║╤Б (QHD) \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n2560x1440 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nIPS LCD \r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass 5 \r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n60 ╨У╤Ж\r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nQualcomm Snapdragon 835 (4 x 2.5 + 4 x 1.8 ╨У╨У╤Ж) \r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno 540 \r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8\r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n64 ╨У╨С \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n4 ╨У╨С \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n2 ╤И╤В\r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n13/13/0/0/0 (╤Ж╨▓╨╡╤В╨╜╨╛╨╣ + ╨╝╨╛╨╜╨╛╤Е╤А╨╛╨╝╨╜╤Л╨╣) \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n3840x2160 ╨Я╨╕╨║╤Б (4K) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n13/13/0/0/0\r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░ (╤Г ╤Ж╨▓╨╡╤В╨╜╨╛╨│╨╛ ╤Б╨╡╨╜╤Б╨╛╤А╨░) \r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n10\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n13 ╨Ь╨Я╨╕╨║╤Б\r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б \r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n13/0 \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\nmicroSD (╨┤╨╛ 256 ╨У╨С) \r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n1 nano-SIM / 2 nano-SIM \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE\r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 5 (802.11ac) \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░ \r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n5.0 \r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░\r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Э╨╡╤В\r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╤Б╨┐╨╡╤А╨╡╨┤╨╕ (╨▓ ╨║╨╜╨╛╨┐╨║╨╡ Home) \r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C (USB 3.1 Gen 1) \r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\n3.5 ╨╝╨╝ \r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╨░╨╗╤О╨╝╨╕╨╜╨╕╨╣ ╤Б╨╡╤А╨╕╨╕ 6000 \r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIP54 (╨╖╨░╤Й╨╕╤В╨░ ╨╛╤В ╨▒╤А╤Л╨╖╨│) \r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Ф╨░ (╤Б ╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨╛╨╣ Quick Charge 3.0)\r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB ╤В╨╕╨┐ ╨Р\r\n╨Ф╨░\r\n╨з╨╡╤Е╨╛╨╗\r\n╨Э╨╡╤В\r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Ф╨░ (╨┐╤А╨╛╨▓╨╛╨┤╨╜╨░╤П ╤Б╤В╨╡╤А╨╡╨╛-╨│╨░╤А╨╜╨╕╤В╤Г╤А╨░)\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n18 ╨Т╤В\r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n3090 ╨╝╨Р╤З 
4	Google Pixel 7 Pro	89990.00	/media/phones/4_Google_Pixel_7_Pro.jpg	2022-10-13	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨Ъ╨╕╤В╨░╨╣ (╤Б╨▒╨╛╤А╨║╨░) / ╨б╨и╨Р (╤А╨░╨╖╤А╨░╨▒╨╛╤В╨║╨░)\r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2022 \r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nGoogle Pixel\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nPixel 7 Pro\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (23 ╨Т╤В) \r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (23 ╨Т╤В) \r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 13 \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.7" / 3120x1440 ╨Я╨╕╨║╤Б \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n3120x1440 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nOLED (LTPO) \r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass Victus \r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n120 ╨У╤Ж \r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nGoogle Tensor G2 (8 ╤П╨┤╨╡╤А, 2.85 ╨У╨У╤Ж) \r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nMali-G710 MC10 \r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8 \r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n128/256/512 ╨У╨С \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n12 ╨У╨С \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n3 ╤И╤В\r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50/48/12/0/0 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n3840x2160 ╨Я╨╕╨║╤Б (4K, 60 FPS) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50 (╤И╨╕╤А╨╛╨║.) / 48 (╤В╨╡╨╗╨╡) / 12 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А╨╛╨║.) \r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░ \r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n30 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n50 ╨Ь╨Я╨╕╨║╤Б \r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo \r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n10.8/0 \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В \r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n1 nano-SIM + eSIM \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE/5G \r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 6E (802.11ax) \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░ \r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n5.2 \r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░\r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Ф╨░ (Face Unlock) \r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╕╨╜╤В╨╡╨│╤А╨╕╤А╨╛╨▓╨░╨╜ ╨▓ ╤Н╨║╤А╨░╨╜ ╤Б╨╝╨░╤А╤В╤Д╨╛╨╜╨░ \r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C 3.2 \r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\nUSB Type-C\r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╤Б╤В╨╡╨║╨╗╨╛/ ╨░╨╗╤О╨╝╨╕╨╜╨╕╨╣ \r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIP68 \r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Э╨╡╤В \r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Ф╨░ \r\n╨з╨╡╤Е╨╛╨╗\r\n╨Э╨╡╤В\r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n23 ╨Т╤В (╨▒╤Л╤Б╤В╤А╨░╤П ╨╖╨░╤А╤П╨┤╨║╨░) \r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n5000 ╨╝╨Р╤З 
5	Xiaomi Mi 11 Ultra	74999.00	/media/phones/5_Xiaomi_Mi_11_Ultra.jpg	2021-04-07	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨Ъ╨╕╤В╨░╨╣\r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2021\r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nXiaomi Mi\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nM2102K1G\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (67 ╨Т╤В)\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (67 ╨Т╤В)\r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 11 (MIUI 12.5, ╨╛╨▒╨╜╨╛╨▓╨╗╤П╨╡╨╝╨░╤П ╨┤╨╛ Android 14)\r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.81" / 3200x1440 ╨Я╨╕╨║╤Б\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n3200x1440 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nAMOLED (E4)\r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass Victus\r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n120 ╨У╤Ж\r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nQualcomm Snapdragon 888 (1 x 2.84 + 3 x 2.42 + 4 x 1.8 ╨У╨У╤Ж)\r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno 660\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8\r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n256 / 512 ╨У╨С\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n12 ╨У╨С\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n3 ╤И╤В\r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50/48/48/0/0\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n7680x4320 ╨Я╨╕╨║╤Б (8K)\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50 (╤И╨╕╤А╨╛╨║.) / 48 (╤В╨╡╨╗╨╡) / 48 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А╨╛╨║.)\r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░\r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n120\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n50 ╨Ь╨Я╨╕╨║╤Б\r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo, Beidou\r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n20/0\r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n2 nano-SIM\r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE/5G\r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 6E (802.11ax)\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n5.2\r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░, ╨┤╨╛╨┐╨╛╨╗╨╜╨╕╤В╨╡╨╗╤М╨╜╤Л╨╣ ╨┤╨╕╤Б╨┐╨╗╨╡╨╣ ╨╜╨░ ╨╖╨░╨┤╨╜╨╡╨╣ ╨┐╨░╨╜╨╡╨╗╨╕\r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Ф╨░\r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╕╨╜╤В╨╡╨│╤А╨╕╤А╨╛╨▓╨░╨╜ ╨▓ ╤Н╨║╤А╨░╨╜ ╤Б╨╝╨░╤А╤В╤Д╨╛╨╜╨░\r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C\r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\nUSB Type-C\r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╤Б╤В╨╡╨║╨╗╨╛ (╨║╨╡╤А╨░╨╝╨╕╨║╨░) / ╨░╨╗╤О╨╝╨╕╨╜╨╕╨╣\r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIP68\r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Ф╨░ (67 ╨Т╤В)\r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Ф╨░\r\n╨з╨╡╤Е╨╛╨╗\r\n╨Ф╨░\r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n67 ╨Т╤В\r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n5000 ╨╝╨Р╤З
6	OnePlus 10 Pro	69990.00	/media/phones/6_OnePlus_10_Pro.jpg	2022-01-11	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨Ъ╨╕╤В╨░╨╣\r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2022 \r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nOnePlus\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nOnePlus 10 Pro\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (80 ╨Т╤В) \r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (50 ╨Т╤В) \r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 12 (OxygenOS / ColorOS) \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.7" / 3216x1440 ╨Я╨╕╨║╤Б \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n3216x1440 ╨Я╨╕╨║╤Б \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nAMOLED (LTPO 2.0) \r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass \r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n120 ╨У╤Ж (╨░╨┤╨░╨┐╤В╨╕╨▓╨╜╨░╤П 1-120 ╨У╤Ж) \r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nQualcomm Snapdragon 8 Gen 1 (8 ╤П╨┤╨╡╤А, 3.0 ╨У╨У╤Ж) \r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno 730 \r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8\r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n128 / 256 ╨У╨С \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n8 / 12 ╨У╨С \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n3 ╤И╤В\r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n48/50/8/0/0 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n7680x4320 ╨Я╨╕╨║╤Б (8K) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n48 (╤И╨╕╤А╨╛╨║.) / 50 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А╨╛╨║.) / 8 (╤В╨╡╨╗╨╡) \r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░ \r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n48 ╨Ь╨Я╨╕╨║╤Б\r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo, Beidou \r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n32/0 \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n2 nano-SIM \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE/5G \r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 6 (802.11ax) \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n5.2 \r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░\r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Ф╨░ \r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╕╨╜╤В╨╡╨│╤А╨╕╤А╨╛╨▓╨░╨╜ ╨▓ ╤Н╨║╤А╨░╨╜ ╤Б╨╝╨░╤А╤В╤Д╨╛╨╜╨░ \r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C\r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\nUSB Type-C \r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╤Б╤В╨╡╨║╨╗╨╛/ ╨╝╨╡╤В╨░╨╗╨╗ \r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Ф╨░ (80 ╨Т╤В) \r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Ф╨░\r\n╨з╨╡╤Е╨╛╨╗\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n80 ╨Т╤В \r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n5000 ╨╝╨Р╤З 
7	Sony Xperia 1 IV	94990.00	/media/phones/7_Sony_Xperia.jpg	2022-06-22	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨п╨┐╨╛╨╜╨╕╤П\r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2026\r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nXperia\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nXperia 1 VIII\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (30 ╨Т╤В)\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (15 ╨Т╤В)\r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 16 \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.5" / 2340x1080 ╨Я╨╕╨║╤Б \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n2340x1080 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nLTPO OLED\r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass Victus 2 \r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n120 ╨У╤Ж\r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nSnapdragon 8 Elite Gen 5\r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno (╨▓╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣)\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8 \r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n256 ╨У╨С / 1 ╨в╨С \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n12 / 16 ╨У╨С \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n3 ╤И╤В\r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n48/48/48/0/0 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n3840x2160 ╨Я╨╕╨║╤Б (4K, 120 FPS) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n48 (╤И╨╕╤А╨╛╨║.) / 48 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А╨╛╨║.) / 48 (╤В╨╡╨╗╨╡)\r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░ \r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\nтЙИ3x (╨╛╨┐╤В╨╕╤З╨╡╤Б╨║╨╕╨╣) \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n48 ╨Ь╨Я╨╕╨║╤Б\r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo\r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n12/0 \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\nmicroSD (╨│╨╕╨▒╤А╨╕╨┤╨╜╤Л╨╣ ╤Б╨╗╨╛╤В) \r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n1 nano-SIM + eSIM / microSD (╨│╨╕╨▒╤А╨╕╨┤╨╜╤Л╨╣) \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE/5G\r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 7 \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n6.0 \r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░\r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Ф╨░\r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨▓╤Б╤В╤А╨╛╨╡╨╜ ╨▓ ╨▒╨╛╨║╨╛╨▓╤Г╤О ╨║╨╜╨╛╨┐╨║╤Г \r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C 3.2 \r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\n3.5 ╨╝╨╝ \r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╤Б╤В╨╡╨║╨╗╨╛/╨╝╨╡╤В╨░╨╗╨╗\r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIP65/IP68 \r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨з╨╡╤Е╨╛╨╗\r\n╨Э╨╡╤В\r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n30 ╨Т╤В \r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n5000 ╨╝╨Р╤З 
8	Huawei P50 Pro	79990.00	/media/phones/8_Huawei_P50.jpg	2021-08-12	f	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨Ъ╨╕╤В╨░╨╣ \r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2021 \r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nHuawei P\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nABR-LX9 \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (66 ╨Т╤В) \r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nHarmonyOS 2.0 \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В \r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.5" / 2700x1224 ╨Я╨╕╨║╤Б \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n2700x1224 ╨Я╨╕╨║╤Б \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nOLED \r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n90 ╨У╤Ж \r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nQualcomm Snapdragon 888 4G (8 ╤П╨┤╨╡╤А, 2.84 ╨У╨У╤Ж) \r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno 660 \r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8\r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n128 / 256 ╨У╨С \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n8 ╨У╨С \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n3 ╤И╤В \r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50/13/12/0/0 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n3840x2160 ╨Я╨╕╨║╤Б (4K) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50 (╨╛╤Б╨╜.) / 13 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А.) / 12 (╤В╨╡╨╗╨╡) \r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░ (╤В╨╡╨╗╨╡╨╛╨▒╤К╨╡╨║╤В╨╕╨▓) \r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n50 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n50 ╨Ь╨Я╨╕╨║╤Б \r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo, Beidou \r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n13/0 \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\nNano Memory (╨┤╨╛ 256 ╨У╨С) \r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n2 nano-SIM \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE \r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 6 (802.11ax) \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░ \r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n5.2 \r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░\r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╕╨╜╤В╨╡╨│╤А╨╕╤А╨╛╨▓╨░╨╜ ╨▓ ╤Н╨║╤А╨░╨╜ ╤Б╨╝╨░╤А╤В╤Д╨╛╨╜╨░ \r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C \r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\nUSB Type-C \r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╤Б╤В╨╡╨║╨╗╨╛/ ╨░╨╗╤О╨╝╨╕╨╜╨╕╨╣ \r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIP68 \r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Ф╨░ (66 ╨Т╤В) \r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Ф╨░\r\n╨з╨╡╤Е╨╛╨╗\r\n╨Ф╨░ (╨┐╤А╨╛╨╖╤А╨░╤З╨╜╤Л╨╣) \r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n66 ╨Т╤В \r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n4100 ╨╝╨Р╤З 
9	Samsung Galaxy A54	35990.00	/media/phones/9_SamsungGalaxy.jpg	2023-03-15	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨о╨╢╨╜╨░╤П ╨Ъ╨╛╤А╨╡╤П / ╨Ъ╨╕╤В╨░╨╣ (╤Б╨▒╨╛╤А╨║╨░) \r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2026 \r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nGalaxy S\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nGalaxy S26 Ultra \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (60 ╨Т╤В) \r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░\r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 16 (One UI) \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.9" / 3120x1440 ╨Я╨╕╨║╤Б \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n3120x1440 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nDynamic AMOLED 2X \r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass Victus 2 \r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n120 ╨У╤Ж \r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nSnapdragon 8 Elite Gen 5 for Galaxy (8 ╤П╨┤╨╡╤А, 4.74 ╨У╨У╤Ж) \r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno (╨▓╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣)\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8\r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n256 ╨У╨С / 1 ╨в╨С \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n12 / 16 ╨У╨С \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n4 ╤И╤В\r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n200/50/10/10/0 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n7680x4320 ╨Я╨╕╨║╤Б (8K) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n200 (╤И╨╕╤А╨╛╨║.) / 50 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А.) / 10 (╤В╨╡╨╗╨╡) / 10 (╤В╨╡╨╗╨╡) \r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░\r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n100 (Space Zoom) \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n200 ╨Ь╨Я╨╕╨║╤Б\r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo, Beidou\r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n12/0 \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n2 nano-SIM / eSIM \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE/5G\r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 7\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n6.0\r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░, Galaxy AI \r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Ф╨░\r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╕╨╜╤В╨╡╨│╤А╨╕╤А╨╛╨▓╨░╨╜ ╨▓ ╤Н╨║╤А╨░╨╜ ╤Б╨╝╨░╤А╤В╤Д╨╛╨╜╨░\r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C 3.2 \r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\nUSB Type-C\r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\nArmour Aluminium / ╤Б╤В╨╡╨║╨╗╨╛ \r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIP68 \r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Э╨╡╤В\r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Ф╨░\r\n╨з╨╡╤Е╨╛╨╗\r\n╨Э╨╡╤В\r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n60 ╨Т╤В (╨░╨┤╨░╨┐╤В╨╡╤А ╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В ╨▓ ╨║╨╛╨╝╨┐╨╗╨╡╨║╤В╨╡) \r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n5000 ╨╝╨Р╤З
10	Realme GT 2 Pro	49990.00	/media/phones/10_Realme_GT2_Pro.jpg	2022-02-28	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨Ъ╨╕╤В╨░╨╣\r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2022 \r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nrealme GT\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nRMX3301\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (65 ╨Т╤В) \r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Э╨╡╤В \r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 12 (realme UI 3.0) \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.7" / 3216x1440 ╨Я╨╕╨║╤Б (WQHD+) \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n3216x1440 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nAMOLED (LTPO 2.0) \r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass Victus \r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n120 ╨У╤Ж (╨░╨┤╨░╨┐╤В╨╕╨▓╨╜╨░╤П 1-120 ╨У╤Ж) \r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nQualcomm Snapdragon 8 Gen 1 (8 ╤П╨┤╨╡╤А, ╨┤╨╛ 3.0 ╨У╨У╤Ж) \r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno 730 \r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8 \r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n256 ╨У╨С (UFS 3.1) \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n12 ╨У╨С (LPDDR5) \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n3 ╤И╤В \r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50/50/2/0/0 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n7680x4320 ╨Я╨╕╨║╤Б (8K) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50 (╤И╨╕╤А╨╛╨║.) / 50 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А. 150┬░) / 2 (╨╝╨╕╨║╤А╨╛╤Б╨║╨╛╨┐) \r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░ (OIS) \r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n50 ╨Ь╨Я╨╕╨║╤Б\r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo, Beidou\r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n32/0 (Sony IMX615) \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В \r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n2 nano-SIM \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE/5G \r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 6 (802.11ax) \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░ \r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n5.2 \r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░\r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Ф╨░ \r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╕╨╜╤В╨╡╨│╤А╨╕╤А╨╛╨▓╨░╨╜ ╨▓ ╤Н╨║╤А╨░╨╜ ╤Б╨╝╨░╤А╤В╤Д╨╛╨╜╨░ \r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C (USB 3.1) \r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\nUSB Type-C \r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╨▒╨╕╨╛╨┐╨╛╨╗╨╕╨╝╨╡╤А (╨╖╨░╨┤╨╜╤П╤П ╨┐╨░╨╜╨╡╨╗╤М) / ╤Б╤В╨╡╨║╨╗╨╛ (╨┐╨╡╤А╨╡╨┤╨╜╤П╤П ╨┐╨░╨╜╨╡╨╗╤М) \r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\n╨Э╨╡╤В \r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Ф╨░ (65 ╨Т╤В) \r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Ф╨░ \r\n╨з╨╡╤Е╨╛╨╗\r\n╨Ф╨░ \r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n65 ╨Т╤В \r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n5000 ╨╝╨Р╤З 
11	Motorola Edge 30 Ultra	64990.00	/media/phones/11_Motorola_Edge_30_Ultra.jpg	2022-09-08	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨Ъ╨╕╤В╨░╨╣ (╤Б╨▒╨╛╤А╨║╨░) / ╨б╨и╨Р (╤А╨░╨╖╤А╨░╨▒╨╛╤В╨║╨░)\r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2022 \r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nMotorola Edge\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nEdge 30 Ultra\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (125 ╨Т╤В) \r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (50 ╨Т╤В) \r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 12 (╨╛╨▒╨╜╨╛╨▓╨╗╤П╨╡╨╝╨░╤П ╨┤╨╛ Android 15) \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.67" / 2400x1080 ╨Я╨╕╨║╤Б \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n2400x1080 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\npOLED \r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass 5 \r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n144 ╨У╤Ж \r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nQualcomm Snapdragon 8+ Gen 1 (8 ╤П╨┤╨╡╤А, ╨┤╨╛ 3.19 ╨У╨У╤Ж) \r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno 730 \r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8\r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n128 / 256 / 512 ╨У╨С (UFS 3.1) \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n8 / 12 ╨У╨С (LPDDR5) \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n3 ╤И╤В \r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n200/50/12/0/0 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n7680x4320 ╨Я╨╕╨║╤Б (8K, 30 FPS) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n200 (╨╛╤Б╨╜.) / 50 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А.) / 12 (╤В╨╡╨╗╨╡) \r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░ (OIS) \r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n200 ╨Ь╨Я╨╕╨║╤Б \r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo, Beidou \r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n60/0 \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В \r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n2 nano-SIM \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE/5G \r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 6E \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░ \r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n5.2 \r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░, Dolby Atmos, ╨╛╨▒╤А╨░╤В╨╜╨░╤П ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨░╤П ╨╖╨░╤А╤П╨┤╨║╨░ (10 ╨Т╤В) \r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Ф╨░ \r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╕╨╜╤В╨╡╨│╤А╨╕╤А╨╛╨▓╨░╨╜ ╨▓ ╤Н╨║╤А╨░╨╜ ╤Б╨╝╨░╤А╤В╤Д╨╛╨╜╨░ \r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C \r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\nUSB Type-C (3.5 ╨╝╨╝ ╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В) \r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╤Б╤В╨╡╨║╨╗╨╛ (Gorilla Glass 5) / ╨╝╨╡╤В╨░╨╗╨╗ \r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIP52 (╨╖╨░╤Й╨╕╤В╨░ ╨╛╤В ╨▒╤А╤Л╨╖╨│) \r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Ф╨░ (125 ╨Т╤В) \r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Ф╨░ \r\n╨з╨╡╤Е╨╛╨╗\r\n╨Ф╨░ (╨┐╤А╨╛╨╖╤А╨░╤З╨╜╤Л╨╣) \r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n125 ╨Т╤В \r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n4610 ╨╝╨Р╤З 
12	Asus ROG Phone 6	84990.00	/media/phones/12_Asus_ROG_Phone_6.jpg	2022-07-05	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨Ъ╨╕╤В╨░╨╣ (╤Б╨▒╨╛╤А╨║╨░) / ╨в╨░╨╣╨▓╨░╨╜╤М (╤А╨░╨╖╤А╨░╨▒╨╛╤В╨║╨░)\r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2022 \r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nROG Phone\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nROG Phone 6\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (65 ╨Т╤В) \r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Э╨╡╤В \r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 12 (╨╛╨▒╨╛╨╗╨╛╤З╨║╨░ ROG) \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨┐╤А╨╕╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В\r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.78" / 2448x1080 ╨Я╨╕╨║╤Б \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n2448x1080 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nAMOLED \r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass Victus \r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n165 ╨У╤Ж \r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nQualcomm Snapdragon 8+ Gen 1 (8 ╤П╨┤╨╡╤А, ╨┤╨╛ 3.2 ╨У╨У╤Ж) \r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno 730 \r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8\r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n256 / 512 ╨У╨С (UFS 3.1) \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n12 / 16 ╨У╨С (LPDDR5) \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n3 ╤И╤В\r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50/13/5/0/0 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n7680x4320 ╨Я╨╕╨║╤Б (8K) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50 (╨╛╤Б╨╜., Sony IMX766) / 13 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А.) / 5 (╨╝╨░╨║╤А╨╛) \r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n50 ╨Ь╨Я╨╕╨║╤Б \r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo, Beidou \r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n12/0 \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В \r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n2 nano-SIM \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE/5G \r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 6E \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░ \r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n5.2 \r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░, ╤Г╨╗╤М╤В╤А╨░╨╖╨▓╤Г╨║╨╛╨▓╤Л╨╡ ╨║╤Г╤А╨║╨╕ AirTrigger \r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╕╨╜╤В╨╡╨│╤А╨╕╤А╨╛╨▓╨░╨╜ ╨▓ ╤Н╨║╤А╨░╨╜ ╤Б╨╝╨░╤А╤В╤Д╨╛╨╜╨░ \r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C (2 ╨┐╨╛╤А╤В╨░: ╤Б╨╜╨╕╨╖╤Г ╨╕ ╤Б╨▒╨╛╨║╤Г) \r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\n3.5 ╨╝╨╝ \r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╤Б╤В╨╡╨║╨╗╨╛ / ╨░╨╗╤О╨╝╨╕╨╜╨╕╨╣ \r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIPX4 (╨╖╨░╤Й╨╕╤В╨░ ╨╛╤В ╨▒╤А╤Л╨╖╨│) \r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Ф╨░ (65 ╨Т╤В) \r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Ф╨░\r\n╨з╨╡╤Е╨╛╨╗\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n65 ╨Т╤В\r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n6000 ╨╝╨Р╤З
13	Nothing Phone (2)	57990.00	/media/phones/13_Nothing_Phone.jpg	2023-07-11	t	╨Ч╨░╨▓╨╛╨┤╤Б╨║╨╕╨╡ ╨┤╨░╨╜╨╜╤Л╨╡\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П\r\n1 ╨│╨╛╨┤\r\n╨У╨░╤А╨░╨╜╤В╨╕╤П ╨┐╤А╨╡╨┤╨╛╤Б╤В╨░╨▓╨╗╤П╨╡╤В╤Б╤П\r\n╨┐╤А╨╛╨╕╨╖╨▓╨╛╨┤╨╕╤В╨╡╨╗╨╡╨╝\r\n╨б╤В╤А╨░╨╜╨░\r\n╨Ъ╨╕╤В╨░╨╣ (╤Б╨▒╨╛╤А╨║╨░) / ╨Т╨╡╨╗╨╕╨║╨╛╨▒╤А╨╕╤В╨░╨╜╨╕╤П (╤А╨░╨╖╤А╨░╨▒╨╛╤В╨║╨░) \r\n╨У╨╛╨┤ ╤А╨╡╨╗╨╕╨╖╨░\r\n2025 \r\n╨б╨╡╤А╨╕╤П ╨╝╨╛╨┤╨╡╨╗╨╕\r\nNothing Phone\r\n╨Ь╨╛╨┤╨╡╨╗╤М\r\nPhone (3)\r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╤Л╨╡ ╤Е╨░╤А╨░╨║╤В╨╡╤А╨╕╤Б╤В╨╕╨║╨╕\r\n╨б╨╛╤Б╤В╨╛╤П╨╜╨╕╨╡\r\n╨╜╨╛╨▓╤Л╨╣\r\n╨Ч╨░╤А╤П╨┤╨║╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (65 ╨Т╤В) \r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╨▒╨╡╤Б╨┐╤А╨╛╨▓╨╛╨┤╨╜╨╛╨╣ ╨╖╨░╤А╤П╨┤╨║╨╕\r\n╨Ф╨░ (15 ╨Т╤В) \r\n\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\n╨Ю╨┐╨╡╤А╨░╤Ж╨╕╨╛╨╜╨╜╨░╤П ╤Б╨╕╤Б╤В╨╡╨╝╨░\r\nAndroid 15 (Nothing OS 3.5) \r\n╨Ю╨▒╤П╨╖. ╨║ ╨┐╤А╨╡╨┤╤Г╤Б╤В╨░╨╜╨╛╨▓╨║╨╡ ╨Я╨Ю\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В (╨┐╨╛╤З╤В╨╕ ╨╜╨╡╤В bloatware) \r\n\r\n╨н╨║╤А╨░╨╜\r\n╨н╨║╤А╨░╨╜\r\n6.67" / 2800x1260 ╨Я╨╕╨║╤Б \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╤Н╨║╤А╨░╨╜╨░\r\n2800x1260 ╨Я╨╕╨║╤Б\r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П ╤Н╨║╤А╨░╨╜╨░\r\nAMOLED (LPTS) \r\n╨в╨╕╨┐ ╤Б╤В╨╡╨║╨╗╨░\r\nCorning Gorilla Glass 7i \r\n╨з╨░╤Б╤В╨╛╤В╨░ ╨╛╨▒╨╜╨╛╨▓╨╗╨╡╨╜╨╕╤П\r\n120 ╨У╤Ж \r\n\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\n╨Я╤А╨╛╤Ж╨╡╤Б╤Б╨╛╤А\r\nQualcomm Snapdragon 8s Gen 4 (8 ╤П╨┤╨╡╤А, ╨┤╨╛ 3.21 ╨У╨У╤Ж) \r\n╨У╤А╨░╤Д╨╕╤З╨╡╤Б╨║╨╕╨╣ ╤Г╤Б╨║╨╛╤А╨╕╤В╨╡╨╗╤М\r\nAdreno 825 \r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤П╨┤╨╡╤А\r\n8\r\n\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (ROM)\r\n256 / 512 ╨У╨С (UFS 4.0) \r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М\r\n╨Ю╨┐╨╡╤А╨░╤В╨╕╨▓╨╜╨░╤П ╨┐╨░╨╝╤П╤В╤М (RAM)\r\n12 / 16 ╨У╨С (LPDDR5X) \r\n\r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╤Б╨╜╨╛╨▓╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n3 ╤И╤В\r\n╨Ю╤Б╨╜. ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50/50/50/0/0 \r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨▓╨╕╨┤╨╡╨╛╤Б╤К╨╡╨╝╨║╨╕\r\n3840x2160 ╨Я╨╕╨║╤Б (4K) \r\n╨Ю╤Б╨╜╨╛╨▓╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50 (╨╛╤Б╨╜.) / 50 (╤Б╨▓╨╡╤А╤Е╤И╨╕╤А.) / 50 (╤В╨╡╨╗╨╡) \r\n╨Ю╨┐╤В╨╕╤З╨╡╤Б╨║╨░╤П ╤Б╤В╨░╨▒╨╕╨╗╨╕╨╖╨░╤Ж╨╕╤П\r\n╨Ф╨░ \r\n╨ж╨╕╤Д╤А╨╛╨▓╨╛╨╣ ╨╖╤Г╨╝ (x)\r\n╨Э╨╡╤В ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨а╨░╨╖╤А╨╡╤И╨╡╨╜╨╕╨╡ ╨╛╤Б╨╜╨╛╨▓╨╜╨╛╨╣ ╨║╨░╨╝╨╡╤А╤Л\r\n50 ╨Ь╨Я╨╕╨║╤Б\r\n\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╤П\r\n╨Э╨░╨▓╨╕╨│╨░╤Ж╨╕╨╛╨╜╨╜╤Л╨╡ ╤Б╨╕╤Б╤В╨╡╨╝╤Л\r\nGPS, ╨У╨Ы╨Ю╨Э╨Р╨б╨б, Galileo, Beidou \r\n\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░\r\n╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╤Д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╤Л╤Е ╨║╨░╨╝╨╡╤А\r\n1 ╤И╤В\r\n╨д╤А╨╛╨╜╤В╨░╨╗╤М╨╜╨░╤П ╨║╨░╨╝╨╡╤А╨░ ╨Ь╨Я╨╕╨║╤Б\r\n50/0 \r\n\r\n╨Ъ╨░╤А╤В╨░ ╨┐╨░╨╝╤П╤В╨╕\r\n╨в╨╕╨┐ ╨║╨░╤А╤В╤Л ╨┐╨░╨╝╤П╤В╨╕\r\n╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В \r\n\r\nSIM ╨║╨░╤А╤В╨░\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ SIM ╨║╨░╤А╤В\r\n2 nano-SIM / eSIM \r\n\r\n╨Я╨╡╤А╨╡╨┤╨░╤З╨░ ╨┤╨░╨╜╨╜╤Л╤Е\r\n╨Я╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ ╤Б╤В╨░╨╜╨┤╨░╤А╤В╨╛╨▓\r\n2G/3G/4G LTE/5G\r\n╨Т╨╡╤А╤Б╨╕╤П Wi-Fi\r\nWi-Fi 7 \r\n╨в╨╡╤Е╨╜╨╛╨╗╨╛╨│╨╕╤П NFC\r\n╨Ф╨░\r\n╨Т╤Б╤В╤А╨╛╨╡╨╜╨╜╤Л╨╣ ╨╝╨╛╨┤╤Г╨╗╤М Bluetooth\r\n6.0 \r\n\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨д╤Г╨╜╨║╤Ж╨╕╨╕\r\n╨┐╨╛╨┤╨┤╨╡╤А╨╢╨║╨░ USB Host (OTG), Wi-Fi ╤В╨╛╤З╨║╨░ ╨┤╨╛╤Б╤В╤Г╨┐╨░, Glyph Mirror (╨┤╨╛╨┐. ╨┤╨╕╤Б╨┐╨╗╨╡╨╣ ╨╜╨░ ╨╖╨░╨┤╨╜╨╡╨╣ ╨┐╨░╨╜╨╡╨╗╨╕) \r\n╨Ф╨░╤В╤З╨╕╨║ ╨╛╤А╨╕╨╡╨╜╤В╨░╤Ж╨╕╨╕ ╤Н╨║╤А╨░╨╜╨░\r\n╨Ф╨░\r\n\r\n╨С╨╡╨╖╨╛╨┐╨░╤Б╨╜╨╛╤Б╤В╤М\r\n╨б╨╡╨╜╤Б╨╛╤А ╤А╨░╤Б╨┐╨╛╨╖╨╜╨░╨▓╨░╨╜╨╕╤П ╨╗╨╕╤Ж╨░\r\n╨Ф╨░\r\n╨б╨║╨░╨╜╨╡╤А ╨╛╤В╨┐╨╡╤З╨░╤В╨║╨░ ╨┐╨░╨╗╤М╤Ж╨░\r\n╨╕╨╜╤В╨╡╨│╤А╨╕╤А╨╛╨▓╨░╨╜ ╨▓ ╤Н╨║╤А╨░╨╜ ╤Б╨╝╨░╤А╤В╤Д╨╛╨╜╨░ \r\n\r\n╨Ш╨╜╤В╨╡╤А╤Д╨╡╨╣╤Б╤Л\r\n╨Я╨╛╤А╤В USB\r\nUSB Type-C \r\n\r\n╨а╨░╨╖╤К╨╡╨╝╤Л\r\n╨а╨░╨╖╤К╨╡╨╝ ╨┤╨╗╤П ╨╜╨░╤Г╤И╨╜╨╕╨║╨╛╨▓\r\nUSB Type-C (3.5 ╨╝╨╝ ╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В) \r\n\r\n╨Ъ╨╛╤А╨┐╤Г╤Б\r\n╨Ь╨░╤В╨╡╤А╨╕╨░╨╗ ╨║╨╛╤А╨┐╤Г╤Б╨░\r\n╤Б╤В╨╡╨║╨╗╨╛/ ╨░╨╗╤О╨╝╨╕╨╜╨╕╨╣ \r\n╨б╤В╨╡╨┐╨╡╨╜╤М ╨╖╨░╤Й╨╕╤В╤Л\r\nIP68 \r\n\r\n╨Ъ╨╛╨╝╨┐╨╗╨╡╨║╤В╨░╤Ж╨╕╤П\r\n╨С╨╗╨╛╨║ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n╨Э╨╡╤В\r\n╨Ъ╨░╨▒╨╡╨╗╤М USB Type-C - USB Type-C\r\n╨Ф╨░ (╨┐╤А╨╛╨╖╤А╨░╤З╨╜╤Л╨╣) \r\n╨з╨╡╤Е╨╛╨╗\r\n╨Э╨╡╤В\r\n╨Э╨░╤Г╤И╨╜╨╕╨║╨╕\r\n╨Э╨╡╤В\r\n\r\n╨н╨╗╨╡╨║╤В╤А╨╛╨┐╨╕╤В╨░╨╜╨╕╨╡\r\n╨Ь╨╛╤Й╨╜╨╛╤Б╤В╤М ╨▒╨╗╨╛╨║╨░ ╨┐╨╕╤В╨░╨╜╨╕╤П\r\n65 ╨Т╤В (╨░╨┤╨░╨┐╤В╨╡╤А ╨╛╤В╤Б╤Г╤В╤Б╤В╨▓╤Г╨╡╤В ╨▓ ╨║╨╛╨╝╨┐╨╗╨╡╨║╤В╨╡)\r\n╨в╨╕╨┐ ╨▓╨╕╨╗╨║╨╕\r\n╨╡╨▓╤А╨╛╤Б╤В╨░╨╜╨┤╨░╤А╤В (╤В╨╕╨┐ E)\r\n╨Х╨╝╨║╨╛╤Б╤В╤М ╨░╨║╨║╤Г╨╝╤Г╨╗╤П╤В╨╛╤А╨░\r\n5080 ╨╝╨Р╤З \r\n\r\n
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 28, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 7, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: main_phone_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_phone_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: main_phone main_phone_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_phone
    ADD CONSTRAINT main_phone_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict UqtN2ksJhBK0oBoSXmuT9aPvw4vgwBgSjad4hrcmiuhePctuDBtTbMeD9u6AMhk


